AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  postgres-connect

  Sample SAM Template for postgres-connect
  
Globals:
  Function:
    Timeout: 3

Resources:
  PGConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: postgres-connect/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /hello
            Method: get

Outputs:
  PGConnectApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  PGConnectFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt PGConnectFunction.Arn
  PGConnectFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt PGConnectFunctionRole.Arn
